/**
 * Назначение: справочник пресетов ограждающих конструкций.
 * Описание: Содержит массив ENVELOPE_PRESETS (стены, утеплители, окна, потолки, полы, кровля) с U или uModel для расчёта по толщине. Экспортирует getEnvelopePresetById(); отдаётся через GET /api/v1/presets/envelope и используется в wallAssembly, heatlossByRooms, validate.
 */

/** @type {import('../types/shared-types.js').EnvelopePreset[]} */
export const ENVELOPE_PRESETS = [
  {
    id: 'wall_gas_concrete_d500',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material: 'Газобетон D500',
    description: 'Несучий шар без утеплювача; U = f(товщина, λ). Утеплення — окремо в параметрах об\'єкта.',
    thicknessOptionsMm: [200, 300, 375, 400, 500],
    uValue: 0.41,
    uModel: { lambdaWmK: 0.14, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_brick_solid',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material: 'Цегла (повнотіла)',
    description: 'Несучий шар (повнотіла цегла), без утеплювача; U за товщиною та λ.',
    thicknessOptionsMm: [250, 380, 510, 640],
    uValue: 1.47,
    uModel: { lambdaWmK: 0.77, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_brick_hollow',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material:
      'Цегла порожиста (1 NF 250*120*65, 1.4 NF 250*120*88, 2.1 NF 250*120*138)',
    description: 'Несучий шар (порожиста цегла/кераміка), без утеплювача; U за товщиною та λ.',
    thicknessOptionsMm: [250, 380, 510, 640],
    uValue: 1.26,
    uModel: { lambdaWmK: 0.4, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_monolithic_concrete_200',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material: 'моноліт-бетон 200 мм',
    description: 'Несучий монолітний бетон, без утеплювача.',
    thicknessOptionsMm: [200],
    uValue: 3.15,
    uModel: { lambdaWmK: 1.7, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_limestone_400',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material: 'вапняк 400 мм',
    description: 'Несучий шар (вапняк), без утеплювача; U за товщиною та λ.',
    thicknessOptionsMm: [400],
    uValue: 1.0,
    uModel: { lambdaWmK: 0.55, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_shell_400',
    kind: 'wall',
    construction: 'зовнішня стіна',
    material: 'ракушняк 400 мм',
    description: 'Несучий шар (ракушняк), без утеплювача; U за товщиною та λ.',
    thicknessOptionsMm: [400],
    uValue: 0.92,
    uModel: { lambdaWmK: 0.5, surfaceR: 0.158, extraR: 0 },
  },
  // УТЕПЛИТЕЛИ (отдельно от несущей стены; один на объект — objectMeta.externalWalls)
  {
    id: 'insul_sftk_pps16f',
    kind: 'insulation',
    construction: 'утеплювач',
    material: 'ППС 16Ф (ПСБ-С 25Ф), СФТК',
    description:
      'Пінополістирол лише в системі СФТК («мокрий фасад»): шар намертво приклеєний і захищений штукатуркою та сіткою (СП 50.13330). λ розрахункова 0,039 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.039, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_50',
    kind: 'insulation',
    construction: 'утеплювач',
    material: 'Мінеральна вата ~50 кг/м³',
    description: 'Відкритий/вентильований фасад. λ 0,045 Вт/(м·К) (ГОСТ 15588-2014, орієнтир).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.045, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_80',
    kind: 'insulation',
    construction: 'утеплювач',
    material: 'Мінеральна вата ~80 кг/м³',
    description: 'Відкритий/вентильований фасад. λ 0,041 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.041, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_100',
    kind: 'insulation',
    construction: 'утеплювач',
    material: 'Мінеральна вата ~100 кг/м³',
    description: 'Відкритий/вентильований фасад. λ 0,039 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.039, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_150',
    kind: 'insulation',
    construction: 'утеплювач',
    material: 'Мінеральна вата ~150 кг/м³',
    description: 'Відкритий/вентильований фасад. λ 0,038 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.038, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'window_pvc_double_chamber_3_glass',
    kind: 'window',
    construction: 'вікно',
    material: 'ПВХ двокамерне (3 скла)',
    description: 'Стандартне ПВХ-вікно: 2 камери/3 скла.',
    uValue: 1.1,
  },
  {
    id: 'window_pvc_triple_chamber_4_glass',
    kind: 'window',
    construction: 'вікно',
    material: 'ПВХ три камери (4 скла)',
    description: 'ПВХ-вікно підвищеної енергоефективності: 3 камери/4 скла.',
    uValue: 0.85,
  },
  {
    id: 'window_pvc_double_chamber_low_e',
    kind: 'window',
    construction: 'вікно',
    material: 'ПВХ двокамерне (3 скла) + енергозберігаюче (I-скло / Low-E)',
    description: 'Low‑E покриття зменшує втрати через склопакет (орієнтовно на 30–50%).',
    uValue: 0.75,
  },
  {
    id: 'window_pvc_triple_chamber_low_e',
    kind: 'window',
    construction: 'вікно',
    material: 'ПВХ три камери (4 скла) + енергозберігаюче (I-скло / Low-E)',
    description: 'Максимальна енергоефективність у лінійці ПВХ: 3 камери/4 скла + Low‑E.',
    uValue: 0.6,
  },
  // ДЕРЕВО / ДЕРЕВО-АЛЮМИНИЙ (окна)
  {
    id: 'window_wood_pine_triple_low_e_argon',
    kind: 'window',
    construction: 'вікно',
    material: 'Дерево (Сосна 78мм) + 3 скла + енергозберігаюче (I-скло) + Аргон',
    uValue: 0.8,
    description: 'Енергоефективне дерев\'яне вікно з м\'якої породи',
  },
  {
    id: 'window_wood_larch_triple_low_e_argon',
    kind: 'window',
    construction: 'вікно',
    material: 'Дерево (Модрина 78мм) + 3 скла + енергозберігаюче (I-скло) + Аргон',
    uValue: 0.9,
    description: 'Оптимальне поєднання міцності та теплоізоляції',
  },
  {
    id: 'window_wood_oak_triple_low_e_argon',
    kind: 'window',
    construction: 'вікно',
    material: 'Дерево (Дуб 78мм) + 3 скла + енергозберігаюче (I-скло) + Аргон',
    uValue: 1.0,
    description: 'Преміальне вікно з твердої породи',
  },
  {
    id: 'window_wood_alu_triple_high_eff',
    kind: 'window',
    construction: 'вікно',
    material: 'Дерево-Алюміній + 3 скла + подвійне енергозбереження + Криптон',
    uValue: 0.7,
    description: 'Максимальний захист зовні та топова теплоізоляція',
  },
  {
    id: 'window_wood_pine_double_std',
    kind: 'window',
    construction: 'вікно',
    material: 'Дерево (Сосна 68мм) + 2 скла (звичайний склопакет)',
    uValue: 1.8,
    description: 'Базове дерев\'яне вікно для дачі або південних регіонів',
  },
  {
    id: 'ceiling_concrete_insulated',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'бетон + утеплювач',
    description: 'Стеля/перекриття з утепленням (орієнтовний U).',
    uValue: 0.18,
  },
  // ПОТОЛКИ / ПЕРЕКРЫТИЯ (добавочные пресеты)
  {
    id: 'ceiling_wood_beams_mineral_wool',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'дерев\'яні балки + мінвата 200мм',
    uValue: 0.19,
    description: 'Стандартне утеплення по дерев\'яних балках',
  },
  {
    id: 'ceiling_wood_beams_max_insulated',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'дерев\'яні балки + мінвата 300мм',
    uValue: 0.13,
    description: 'Посилене утеплення для мінімізації втрат',
  },
  {
    id: 'ceiling_precast_monolithic_insulated',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'збірно-монолітне (газобетон/кераміка) + утеплювач',
    uValue: 0.16,
    description: 'Сучасне перекриття з високими тепловими характеристиками',
  },
  {
    id: 'ceiling_concrete_pir_insulated',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'бетон + PIR-плита (поліїзоціанурат)',
    uValue: 0.14,
    description: 'Мінімальна товщина при максимальному енергозбереженні',
  },
  {
    id: 'ceiling_concrete_no_insulation',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'бетон (міжповерхове без утеплення)',
    uValue: 2.5,
    description: 'Використовується лише якщо зверху тепле житлове приміщення',
  },
  // ПОТОЛКИ ИЗ ГКЛ (подвесные/каркасные системы)
  {
    id: 'ceiling_gkl_minwool_std',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'ГКЛ + каркас із заповненням мінватою (100-150мм)',
    uValue: 0.28,
    description: 'Стандартна підвісна стеля з тепло-звукоізоляцією',
  },
  {
    id: 'ceiling_gkl_air_gap',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'ГКЛ + замкнена повітряна прослойка',
    uValue: 1.2,
    description:
      'Декоративна стеля між теплими приміщеннями (topBoundary=heated); не використовувати при unheated зверху.',
  },
  // Межэтажные перекрытия квартиры в МКД (теплый контур — U≈0)
  {
    id: 'floor_interstory_apartment',
    kind: 'floor',
    construction: 'підлога',
    material: 'міжповерхове перекриття (квартира/сусіди)',
    uValue: 0,
    description: 'Знизу та зверху теплий контур — тепловтрати через підлогу не враховуються.',
  },
  {
    id: 'ceiling_interstory_apartment',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'міжповерхове перекриття (квартира/сусіди)',
    uValue: 0,
    description: 'Зверху тепле приміщення — тепловтрати через стелю не враховуються.',
  },
  {
    id: 'floor_apt_over_cold_below',
    kind: 'floor',
    construction: 'підлога',
    material: 'плита над підвалом/неопалюваною зоною + утеплювач',
    uValue: 0.32,
    description: 'Перший поверх квартири в стояку: підлога над холодною зоною знизу.',
  },
  {
    id: 'ceiling_apt_under_attic',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'перекриття під горищем/покриттям + мінвата',
    uValue: 0.3,
    description: 'Останній поверх квартири: утеплене перекриття під холодною зоною зверху.',
  },
  {
    id: 'ceiling_concrete_gkl_finish',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'Бетон + утеплювач зовні + оздоблення ГКЛ всередині',
    uValue: 0.17,
    description: 'Комбінована конструкція: бетон утримує тепло, ГКЛ для оздоблення',
  },
  {
    id: 'ceiling_gkl_ecowool',
    kind: 'ceiling',
    construction: 'стеля',
    material: 'ГКЛ + задувна ековата (200мм)',
    uValue: 0.2,
    description: 'Безшовне утеплення над гіпсокартонним листом',
  },
  // КРОВЛЯ / СОВМЕЩЁННОЕ ПОКРЫТИЕ (наружу)
  {
    id: 'roof_concrete_insulated_flat',
    kind: 'roof',
    construction: 'комбіноване покриття',
    material: 'з/б плита + утеплювач',
    uValue: 0.16,
    description: 'Безгорищне покриття (орієнтир U: 0.15–0.18).',
  },
  {
    id: 'roof_mansard_insulated',
    kind: 'roof',
    construction: 'мансардне покриття',
    material: 'бетон/крокви + утеплювач + вентзазор',
    uValue: 0.14,
    description: 'Орієнтир U: 0.12–0.15 (залежить від утеплення та вузлів).',
  },
  {
    id: 'roof_concrete_combined',
    kind: 'roof',
    construction: 'комбіноване покриття',
    material: 'з/б плита + утеплювач (ППС/вата)',
    description:
      'Безгорищне плоске покриття. Розрахунок з урахуванням тепловіддачі зовнішньої поверхні.',
    uValue: 0.17,
  },
  {
    id: 'roof_mansard_concrete',
    kind: 'roof',
    construction: 'мансардне покриття',
    material: 'бетон + утеплювач + вентзазор',
    description:
      'Утеплене скатне покриття. U-value нижче через підвищені вимоги до теплозахисту горищних зон.',
    uValue: 0.14,
  },
  {
    id: 'floor_concrete_uninsulated',
    kind: 'floor',
    construction: 'підлога',
    material: 'бетон без утеплення',
    description: 'Підлога без утеплення — високий U (великі втрати).',
    uValue: 0.6,
  },
  // Типовые «пироги» пола по бетонной плите (переезд пользовательских вариантов вверх списка)
  {
    id: 'floor_slab_rough_screed_eps_finish_screed_porcelain',
    kind: 'floor',
    construction: 'підлога',
    material:
      'бетонна плита + чорнова стяжка + ЕППС + чистова стяжка + керамограніт',
    uValue: 0.35,
    description:
      'Орієнтир U при типовій товщині ЕППС: фактичний U залежить від товщини утеплювача та вузлів.',
  },
  {
    id: 'floor_slab_rough_screed_porcelain',
    kind: 'floor',
    construction: 'підлога',
    material: 'бетонна плита + чорнова стяжка + керамограніт',
    uValue: 0.75,
    description:
      'Без шару ефективного утеплювача — підвищені тепловтрати через підлогу.',
  },
  {
    id: 'floor_slab_finish_screed_parquet',
    kind: 'floor',
    construction: 'підлога',
    material: 'бетонна плита + чистова стяжка + паркетна дошка',
    uValue: 0.55,
    description:
      'Орієнтир для «плаваючої» стяжки та інженерної дошки; λ і товщини впливають на U.',
  },
  // ПОЛЫ (добавочные пресеты)
  {
    id: 'floor_ground_eps_100',
    kind: 'floor',
    construction: 'підлога',
    material: 'підлога по грунту + ЕППС 100мм',
    uValue: 0.3,
    description: 'Стандартна енергоефективна підлога по бетонній основі.',
  },
  {
    id: 'floor_wood_joists_insulated',
    kind: 'floor',
    construction: 'підлога',
    material: 'дерев\'яні лаги + мінвата 200мм',
    uValue: 0.22,
    description: 'Утеплене перекриття над холодним підпідлоговим простором.',
  },
  {
    id: 'floor_sweden_plate_pir',
    kind: 'floor',
    construction: 'підлога',
    material: 'утеплена шведська плита (PIR/ЕППС 200мм)',
    uValue: 0.15,
    description: 'Максимальне утеплення фундаменту, мінімальні втрати.',
  },
  {
    id: 'floor_concrete_slab_eps_50',
    kind: 'floor',
    construction: 'підлога',
    material: 'бетонна плита + ЕППС 50мм',
    uValue: 0.55,
    description: 'Мінімальне утеплення плити перекриття.',
  },
  {
    id: 'floor_interior_no_insulation',
    kind: 'floor',
    construction: 'підлога',
    material: 'бетон/дерево (між жилими поверхами)',
    uValue: 0,
    description: 'Втрати тепла не враховуються, оскільки знизу тепле приміщення.',
  },
];

/**
 * @param {string} presetId
 * @returns {import('../types/shared-types.js').EnvelopePreset | null}
 */
export function getEnvelopePresetById(presetId) {
  if (!presetId) return null;
  // Сборки ТП (underfloor_heating_*) — в warmFloorAssemblyPresets.js, не здесь.
  if (String(presetId).startsWith('underfloor_heating_')) return null;
  return ENVELOPE_PRESETS.find((p) => p.id === presetId) ?? null;
}
