/**
 * Назначение: справочник пресетов ограждающих конструкций.
 * Описание: Содержит массив ENVELOPE_PRESETS (стены, утеплители, окна, потолки, полы, кровля) с U или uModel для расчёта по толщине. Экспортирует getEnvelopePresetById(); отдаётся через GET /api/v1/presets/envelope и используется в wallAssembly, heatlossByRooms, validate.
 */

/** @type {import('../types/shared-types').EnvelopePreset[]} */
export const ENVELOPE_PRESETS = [
  {
    id: 'wall_gas_concrete_d500',
    kind: 'wall',
    construction: 'наружная стена',
    material: 'Газобетон D500',
    description: 'Несущий слой без утеплителя; U = f(толщина, λ). Утепление — отдельно в параметрах объекта.',
    thicknessOptionsMm: [200, 300, 375, 400, 500],
    uValue: 0.41,
    uModel: { lambdaWmK: 0.14, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_brick_solid',
    kind: 'wall',
    construction: 'наружная стена',
    material: 'Кирпич (полнотелый)',
    description: 'Несущий слой (полнотелый кирпич), без утеплителя; U по толщине и λ.',
    thicknessOptionsMm: [250, 380, 510, 640],
    uValue: 1.47,
    uModel: { lambdaWmK: 0.77, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_brick_hollow',
    kind: 'wall',
    construction: 'наружная стена',
    material:
      'Кирпич пустотелый (1 NF 250*120*65, 1.4 NF 250*120*88, 2.1 NF 250*120*138)',
    description: 'Несущий слой (пустотелый кирпич/керамика), без утеплителя; U по толщине и λ.',
    thicknessOptionsMm: [250, 380, 510, 640],
    uValue: 1.26,
    uModel: { lambdaWmK: 0.4, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_monolithic_concrete_200',
    kind: 'wall',
    construction: 'наружная стена',
    material: 'монолит-бетон 200 мм',
    description: 'Несущий монолитный бетон, без утеплителя.',
    thicknessOptionsMm: [200],
    uValue: 3.15,
    uModel: { lambdaWmK: 1.7, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_limestone_400',
    kind: 'wall',
    construction: 'наружная стена',
    material: 'известняк 400 мм',
    description: 'Несущий слой (известняк), без утеплителя; U по толщине и λ.',
    thicknessOptionsMm: [400],
    uValue: 1.0,
    uModel: { lambdaWmK: 0.55, surfaceR: 0.158, extraR: 0 },
  },
  {
    id: 'wall_shell_400',
    kind: 'wall',
    construction: 'наружная стена',
    material: 'ракушечник 400 мм',
    description: 'Несущий слой (ракушечник), без утеплителя; U по толщине и λ.',
    thicknessOptionsMm: [400],
    uValue: 0.92,
    uModel: { lambdaWmK: 0.5, surfaceR: 0.158, extraR: 0 },
  },
  // УТЕПЛИТЕЛИ (отдельно от несущей стены; один на объект — objectMeta.externalWalls)
  {
    id: 'insul_sftk_pps16f',
    kind: 'insulation',
    construction: 'утеплитель',
    material: 'ППС 16Ф (ПСБ-С 25Ф), СФТК',
    description:
      'Пенополистирол только в системе СФТК («мокрый фасад»): слой намертво приклеен и защищён штукатуркой и сеткой (СП 50.13330). λ расчётная 0,039 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.039, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_50',
    kind: 'insulation',
    construction: 'утеплитель',
    material: 'Минеральная вата ~50 кг/м³',
    description: 'Открытый/вентилируемый фасад. λ 0,045 Вт/(м·К) (ГОСТ 15588-2014, ориентир).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.045, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_80',
    kind: 'insulation',
    construction: 'утеплитель',
    material: 'Минеральная вата ~80 кг/м³',
    description: 'Открытый/вентилируемый фасад. λ 0,041 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.041, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_100',
    kind: 'insulation',
    construction: 'утеплитель',
    material: 'Минеральная вата ~100 кг/м³',
    description: 'Открытый/вентилируемый фасад. λ 0,039 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.039, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'insul_minwool_150',
    kind: 'insulation',
    construction: 'утеплитель',
    material: 'Минеральная вата ~150 кг/м³',
    description: 'Открытый/вентилируемый фасад. λ 0,038 Вт/(м·К).',
    thicknessOptionsMm: [50, 80, 100, 120, 150, 200],
    uModel: { lambdaWmK: 0.038, surfaceR: 0, extraR: 0 },
  },
  {
    id: 'window_pvc_double_chamber_3_glass',
    kind: 'window',
    construction: 'окно',
    material: 'ПВХ двухкамерное (3 стекла)',
    description: 'Стандартное ПВХ-окно: 2 камеры/3 стекла.',
    uValue: 1.1,
  },
  {
    id: 'window_pvc_triple_chamber_4_glass',
    kind: 'window',
    construction: 'окно',
    material: 'ПВХ трехкамерный (4 стекла)',
    description: 'ПВХ-окно повышенной энергоэффективности: 3 камеры/4 стекла.',
    uValue: 0.85,
  },
  {
    id: 'window_pvc_double_chamber_low_e',
    kind: 'window',
    construction: 'окно',
    material: 'ПВХ двухкамерное (3 стекла) + энергосберегающее (I-стекло / Low-E)',
    description: 'Low‑E покрытие снижает потери через стеклопакет (ориентировочно на 30–50%).',
    uValue: 0.75,
  },
  {
    id: 'window_pvc_triple_chamber_low_e',
    kind: 'window',
    construction: 'окно',
    material: 'ПВХ трехкамерный (4 стекла) + энергосберегающее (I-стекло / Low-E)',
    description: 'Максимальная энергоэффективность в линейке ПВХ: 3 камеры/4 стекла + Low‑E.',
    uValue: 0.6,
  },
  // ДЕРЕВО / ДЕРЕВО-АЛЮМИНИЙ (окна)
  {
    id: 'window_wood_pine_triple_low_e_argon',
    kind: 'window',
    construction: 'окно',
    material: 'Дерево (Сосна 78мм) + 3 стекла + энергосберегающее (I-стекло) + Аргон',
    uValue: 0.8,
    description: 'Энергоэффективное деревянное окно из мягкой породы',
  },
  {
    id: 'window_wood_larch_triple_low_e_argon',
    kind: 'window',
    construction: 'окно',
    material: 'Дерево (Лиственница 78мм) + 3 стекла + энергосберегающее (I-стекло) + Аргон',
    uValue: 0.9,
    description: 'Оптимальное сочетание прочности и теплоизоляции',
  },
  {
    id: 'window_wood_oak_triple_low_e_argon',
    kind: 'window',
    construction: 'окно',
    material: 'Дерево (Дуб 78мм) + 3 стекла + энергосберегающее (I-стекло) + Аргон',
    uValue: 1.0,
    description: 'Премиальное окно из твердой породы',
  },
  {
    id: 'window_wood_alu_triple_high_eff',
    kind: 'window',
    construction: 'окно',
    material: 'Дерево-Алюминий + 3 стекла + двойное энергосбережение + Криптон',
    uValue: 0.7,
    description: 'Максимальная защита снаружи и топовая теплоизоляция',
  },
  {
    id: 'window_wood_pine_double_std',
    kind: 'window',
    construction: 'окно',
    material: 'Дерево (Сосна 68мм) + 2 стекла (обычный стеклопакет)',
    uValue: 1.8,
    description: 'Базовое деревянное окно для дачи или южных регионов',
  },
  {
    id: 'ceiling_concrete_insulated',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'бетон + утеплитель',
    description: 'Потолок/перекрытие с утеплением (ориентировочный U).',
    uValue: 0.18,
  },
  // ПОТОЛКИ / ПЕРЕКРЫТИЯ (добавочные пресеты)
  {
    id: 'ceiling_wood_beams_mineral_wool',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'деревянные балки + минвата 200мм',
    uValue: 0.19,
    description: 'Стандартное утепление по деревянным балкам',
  },
  {
    id: 'ceiling_wood_beams_max_insulated',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'деревянные балки + минвата 300мм',
    uValue: 0.13,
    description: 'Усиленное утепление для минимизации потерь',
  },
  {
    id: 'ceiling_precast_monolithic_insulated',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'сборно-монолитное (газобетон/керамика) + утеплитель',
    uValue: 0.16,
    description: 'Современное перекрытие с высокими тепловыми характеристиками',
  },
  {
    id: 'ceiling_concrete_pir_insulated',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'бетон + PIR-плита (полиизоцианурат)',
    uValue: 0.14,
    description: 'Минимальная толщина при максимальном энергосбережении',
  },
  {
    id: 'ceiling_concrete_no_insulation',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'бетон (межэтажное без утепления)',
    uValue: 2.5,
    description: 'Используется только если сверху теплое жилое помещение',
  },
  // ПОТОЛКИ ИЗ ГКЛ (подвесные/каркасные системы)
  {
    id: 'ceiling_gkl_minwool_std',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'ГКЛ + каркас с заполнением минватой (100-150мм)',
    uValue: 0.28,
    description: 'Стандартный подвесной потолок с тепло-звукоизоляцией',
  },
  {
    id: 'ceiling_gkl_air_gap',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'ГКЛ + замкнутая воздушная прослойка',
    uValue: 1.2,
    description:
      'Декоративный потолок между тёплыми помещениями (topBoundary=heated); не использовать при unheated сверху.',
  },
  // Межэтажные перекрытия квартиры в МКД (теплый контур — U≈0)
  {
    id: 'floor_interstory_apartment',
    kind: 'floor',
    construction: 'пол',
    material: 'межэтажное перекрытие (квартира/соседи)',
    uValue: 0,
    description: 'Снизу и сверху тёплый контур — теплопотери через пол не учитываются.',
  },
  {
    id: 'ceiling_interstory_apartment',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'межэтажное перекрытие (квартира/соседи)',
    uValue: 0,
    description: 'Сверху тёплое помещение — теплопотери через потолок не учитываются.',
  },
  {
    id: 'floor_apt_over_cold_below',
    kind: 'floor',
    construction: 'пол',
    material: 'плита над подвалом/неотапливаемой зоной + утеплитель',
    uValue: 0.32,
    description: 'Первый этаж квартиры в стояке: пол над холодной зоной снизу.',
  },
  {
    id: 'ceiling_apt_under_attic',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'перекрытие под чердаком/кровлей + минвата',
    uValue: 0.3,
    description: 'Последний этаж квартиры: утеплённое перекрытие под холодной зоной сверху.',
  },
  {
    id: 'ceiling_concrete_gkl_finish',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'Бетон + утеплитель снаружи + отделка ГКЛ внутри',
    uValue: 0.17,
    description: 'Комбинированная конструкция: бетон держит тепло, ГКЛ для отделки',
  },
  {
    id: 'ceiling_gkl_ecowool',
    kind: 'ceiling',
    construction: 'потолок',
    material: 'ГКЛ + задувная эковата (200мм)',
    uValue: 0.2,
    description: 'Бесшовное утепление над гипсокартонным листом',
  },
  // КРОВЛЯ / СОВМЕЩЁННОЕ ПОКРЫТИЕ (наружу)
  {
    id: 'roof_concrete_insulated_flat',
    kind: 'roof',
    construction: 'совмещенное покрытие',
    material: 'ж/б плита + утеплитель',
    uValue: 0.16,
    description: 'Бесчердачное покрытие (ориентир U: 0.15–0.18).',
  },
  {
    id: 'roof_mansard_insulated',
    kind: 'roof',
    construction: 'мансардная кровля',
    material: 'бетон/стропила + утеплитель + вентзазор',
    uValue: 0.14,
    description: 'Ориентир U: 0.12–0.15 (зависит от утепления и узлов).',
  },
  {
    id: 'roof_concrete_combined',
    kind: 'roof',
    construction: 'совмещенное покрытие',
    material: 'ж/б плита + утеплитель (ППС/вата)',
    description:
      'Бесчердачная плоская кровля. Расчет с учетом теплоотдачи наружной поверхности.',
    uValue: 0.17,
  },
  {
    id: 'roof_mansard_concrete',
    kind: 'roof',
    construction: 'мансардное покрытие',
    material: 'бетон + утеплитель + вентзазор',
    description:
      'Утепленная скатная кровля. U-value ниже из-за повышенных требований к теплозащите чердачных зон.',
    uValue: 0.14,
  },
  {
    id: 'floor_concrete_uninsulated',
    kind: 'floor',
    construction: 'пол',
    material: 'бетон без утепления',
    description: 'Пол без утепления — высокий U (большие потери).',
    uValue: 0.6,
  },
  // Типовые «пироги» пола по бетонной плите (переезд пользовательских вариантов вверх списка)
  {
    id: 'floor_slab_rough_screed_eps_finish_screed_porcelain',
    kind: 'floor',
    construction: 'пол',
    material:
      'бетонная плита + черновая стяжка + ЭППС + чистовая стяжка + керамогранит',
    uValue: 0.35,
    description:
      'Ориентир U при типовой толщине ЭППС: фактический U зависит от толщины утеплителя и узлов.',
  },
  {
    id: 'floor_slab_rough_screed_porcelain',
    kind: 'floor',
    construction: 'пол',
    material: 'бетонная плита + черновая стяжка + керамогранит',
    uValue: 0.75,
    description:
      'Без слоя эффективного утеплителя — повышенные теплопотери через пол.',
  },
  {
    id: 'floor_slab_finish_screed_parquet',
    kind: 'floor',
    construction: 'пол',
    material: 'бетонная плита + чистовая стяжка + паркетная доска',
    uValue: 0.55,
    description:
      'Ориентир для «плавающей» стяжки и инженерной доски; λ и толщины влияют на U.',
  },
  // ПОЛЫ (добавочные пресеты)
  {
    id: 'floor_ground_eps_100',
    kind: 'floor',
    construction: 'пол',
    material: 'пол по грунту + ЭППС 100мм',
    uValue: 0.3,
    description: 'Стандартный энергоэффективный пол по бетонному основанию.',
  },
  {
    id: 'floor_wood_joists_insulated',
    kind: 'floor',
    construction: 'пол',
    material: 'деревянные лаги + минвата 200мм',
    uValue: 0.22,
    description: 'Утепленное перекрытие над холодным подпольем.',
  },
  {
    id: 'floor_sweden_plate_pir',
    kind: 'floor',
    construction: 'пол',
    material: 'утепленная шведская плита (PIR/ЭППС 200мм)',
    uValue: 0.15,
    description: 'Максимальное утепление фундамента, минимальные потери.',
  },
  {
    id: 'floor_concrete_slab_eps_50',
    kind: 'floor',
    construction: 'пол',
    material: 'бетонная плита + ЭППС 50мм',
    uValue: 0.55,
    description: 'Минимальное утепление плиты перекрытия.',
  },
  {
    id: 'floor_interior_no_insulation',
    kind: 'floor',
    construction: 'пол',
    material: 'бетон/дерево (между жилыми этажами)',
    uValue: 0,
    description: 'Потери тепла не считаются, так как снизу теплое помещение.',
  },
];

/**
 * @param {string} presetId
 * @returns {import('../types/shared-types').EnvelopePreset | null}
 */
export function getEnvelopePresetById(presetId) {
  if (!presetId) return null;
  // Сборки ТП (underfloor_heating_*) — в warmFloorAssemblyPresets.js, не здесь.
  if (String(presetId).startsWith('underfloor_heating_')) return null;
  return ENVELOPE_PRESETS.find((p) => p.id === presetId) ?? null;
}
